### ISSUE TITLE
cpu/memory 前置检查，并给出友好的提示

### ISSUE THREAD

**Issue by heimanba** [devsapp/start-sae#10]
![image](https://user-images.githubusercontent.com/5129967/182578175-2b25c08e-8c53-4eea-886a-e9f072788ee3.png)

这里我给出cpu为2000 ,memory 没有给出，但是其实默认的值为1024。

这里期望能够给出友好提示，或者 比如CPU为2000,默认的memory 应该为 2048

**Comment by Joycepy** [comment]
已修复，根据cpu自动调整memory的默认值
